baseurl: ""
url: "https://firelord1.github.io"
permalink: /:title/

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

 # Plug-ins
plugins:
  - jekyll-sitemap # Creates a sitemap using the official Jekyll sitemap gem