baseURL = 'https://theamankumar.tech'
languageCode = 'en-us'
title = 'Home'
[markup.highlight]
    codeFences = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 4
