baseURL = 'http://firelord.github.io'
languageCode = 'en-us'
title = 'Home'
description = "Hi! This is Aman Kumar's portfolio website, here I post about my project demos and blogs"
[markup.highlight]
    codeFences = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 4